### ISSUE TITLE
Doesn't read doker environment variables

### ISSUE THREAD

**Issue by pashak09** [motdotla/dotenv#433]
Doesn't read docker environment variables, or is it a library that only reads from a file?

```
  node:
    build:
      context: .
      <<: *cache
      dockerfile: ./docker/node/Dockerfile
    shm_size: 1gb
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - ./block/:/home/app/:rw
```

```
conlose.log(process.env);
{ HOME: '/root',
  LOGNAME: 'root',
  PATH: '/usr/bin:/bin',
  SHELL: '/bin/sh',
  PWD: '/root' }
```
